language: node_js
node_js:
  - "8"

sudo: required

dist: trusty

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - npm install

script:
  - testrpc &
  - truffle test
