language: node_js
node_js:
  - "8"

sudo: required

dist: trusty

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - npm install

script:
  - testrpc &
  - truffle test
  - truffle compile
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
