language: node_js
nodejs:
  

sudo: required

dist: trusty

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - npm install

script:
  - testrpc &
  - truffle test
