# dapp-demo3
Example dapp for storing your personal data like email, name and age.

image:https://travis-ci.org/stoutsource/dapp-demo3.svg?branch=master["Build Status", link="https://travis-ci.org/stoutsource/dapp-demo3"]

## Features
On the left part of your screen you can see all users who updated their personal information (email, name and age). If you already updated your own information, your id should be highlighted with a distinct color.

On the right part of you screen you see fields to edit your personal email, name and age. By clicking `Update` button the data will be stored on the blockchain.

## Development
### How to setup ethereum node for development

Seems that all you need is to setup and run the latest `testrpc` ethereum network emulator https://github.com/ethereumjs/testrpc

### Setup node.js dev environment
1. Install [truffle](https://github.com/trufflesuite/truffle)
2. Then run `truffle compile`, then run `truffle migrate` to deploy the contracts onto your network of choice (default "development").
3. Then run `npm run dev` to build the app and serve it on http://localhost:8080

### web3.js notice

Currently unable upgrade to web3.js v1.x.x due the following reasons:
* `ganacha-core` (testrpc) doesn't support WS connection yet while v1.x.x requires it https://github.com/trufflesuite/ganache-core/pull/14
* `truffle` doesn't support web-packed v1.x.x requiring a lot of broken dependencies

## Production
### Building static app

[source,shell]
.Using pre-configured npm build script
----
npm run build
----

### Docker deployment
WARNING: Make sure that you have pre-built static app in `build` folder. If you don't, check out the section above.

#### Build container image from existing build

[source,shell]
.Build a new version of docker image with
----
docker build -t stoutsource/dapp-demo3 .
----

[source,shell]
.And run it
----
docker run -p 8080:80 stoutsource/dapp-demo3
----
